project:
  type: website

website:
  title: "NeuraPals Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: main_walkthrough.qmd
        text: Main
      - href: voice_recorder_walkthrough.qmd
        text: Voice Recorder

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
